[package]
authors = ["Taryn <taryn@phrohdoh.com>"]
name = "flrt"
version = "0.0.1"
description = "Allows addition/removal of dependencies to/from a `pubspec.yaml` file for Flutter projects"

[dependencies]
clap = "*"
reqwest = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
serde_yaml = "*"
